name: Check for upstream update

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: {}

concurrency:
  group: check-update
  cancel-in-progress: false

jobs:
  check-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Check for upstream update
        run: ./update.sh
